In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.cross_validation import  cross_val_score
%matplotlib inline
from sklearn.model_selection import train_test_split

/home/harsh/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
train_set=pd.read_csv('JPM1.csv')
test_set=pd.read_csv('JPM_test.csv')

In [3]:
y=train_set['MACD'].astype(int)
X=train_set.drop(labels=['MACD','Average_Loss','Loss','Volume'],axis=1)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [5]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()

In [6]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [7]:
predictions = dtree.predict(X_test)

In [8]:
print(accuracy_score(y_test,predictions))

0.8816793893129771


In [9]:
print(confusion_matrix(y_test,predictions))

[[445  32]
 [ 30  17]]


ValueError: Number of features of the model must match the input. Model n_features is 13 and input n_features is 16 

In [19]:
comp=pd.read_csv('JPM_test_OP.csv')

In [ ]:
pre1=dtree.predict(test_set)

In [12]:
print(confusion_matrix(comp['MACD'],pre1))

[[220  13]
 [ 11   6]]


In [13]:
print(accuracy_score(comp['MACD'],pre1))

0.904


In [15]:
comp['MACD'].value_counts()

0    233
1     17
Name: MACD, dtype: int64

In [11]:
test_set.drop(labels=['Volume','Average_Loss','Loss'],axis=1,inplace=True)

In [23]:
cnt=0
for i in y_test:
    if i==1:
        cnt+=1
print(cnt)

46


In [12]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [13]:
rfc_pred = rfc.predict(X_test)

print(confusion_matrix(y_test,rfc_pred))

print(accuracy_score(y_test,rfc_pred)*100)

In [17]:
p1=rfc.predict(test_set)

In [22]:
print(accuracy_score(comp['MACD'],p1)*100)

92.0


In [21]:
print(confusion_matrix(comp['MACD'],p1))

[[225   8]
 [ 12   5]]
