In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.cross_validation import  cross_val_score
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn import metrics

/home/harsh/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
train_set=pd.read_csv('JPM1.csv')
test_set=pd.read_csv('JPM_test.csv')
y=train_set['MACD'].astype(int)
X=train_set.drop(labels=['MACD','Volume','Average_Loss','Loss'],axis=1)
test_set.drop(labels=['Volume','Average_Loss','Loss'],axis=1,inplace=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=30)

In [5]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=30, p=2,
           weights='uniform')

In [6]:
pred = knn.predict(X_test)

print(confusion_matrix(y_test,pred))

In [9]:
print(accuracy_score(y_test.astype(int),pred)*100)

90.2671755725191


In [10]:
predictions=knn.predict(test_set)

In [11]:
comp=pd.read_csv('JPM_test_OP.csv')

In [12]:
print(accuracy_score(comp['MACD'],predictions)*100)

93.2


In [13]:
print(confusion_matrix(comp['MACD'],predictions))

[[233   0]
 [ 17   0]]


In [133]:
np.exp(predictions)

array([20.08553692, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 20.08553692, 20.08553692, 20.08553692,
       20.08553692, 54.59815003, 20.08553692, 54.59815003, 54.59815003,
       20.08553692, 20.08553692, 54.59815003, 54.59815003, 20.08553692,
       54.59815003, 54.59815003, 20.08553692, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 20.08553692, 20.08553692,
       20.08553692, 20.08553692, 20.08553692, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 20.08553692,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 20.08553692,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 20.08553692, 54.59815003, 20.08553692, 20.08553692,
       20.08553692, 20.08553692, 54.59815003, 20.08553692, 54.59815003,
       54.59815003, 20.08553692, 20.08553692, 54.59815003, 20.08553692,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59

In [14]:
from sklearn.svm import SVC

In [15]:
model = SVC()

In [77]:
y_train

146     3.410227
1028    3.925572
919     3.801021
130     3.530315
802     3.760621
1065    3.931500
71      3.539074
689     3.602083
266     3.680060
387     3.426654
279     3.653358
110     3.451967
1376    4.173861
824     3.767989
368     3.512529
1529    4.002349
1450    4.125844
1009    3.891186
1348    4.136855
861     3.849130
849     3.848094
1687    4.196299
296     3.648838
1186    3.933365
1117    3.935436
1334    4.134321
137     3.439574
1737    4.435273
847     3.849035
752     3.722666
          ...   
1093    3.922382
211     3.433139
1099    3.946514
621     3.409977
675     3.566534
1061    3.914086
1480    4.134352
192     3.421305
679     3.591815
614     3.378330
684     3.608950
135     3.442753
90      3.422969
1138    3.933470
249     3.616386
1375    4.173139
1621    4.089389
84      3.460509
1344    4.129684
945     3.852675
1706    4.219022
541     3.638941
1616    4.086635
956     3.886323
1054    3.977753
14      3.497324
876     3.919157
980     3.9370

In [16]:
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
pred = model.predict(X_test)

In [19]:
print(confusion_matrix(y_test,pred))

[[472   1]
 [ 51   0]]


In [20]:
predictions=model.predict(test_set)

In [21]:
print(accuracy_score(comp['MACD'],predictions)*100)

93.2


In [22]:
print(confusion_matrix(comp['MACD'],predictions))

[[233   0]
 [ 17   0]]


In [52]:
np.exp(predictions)

array([54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59815003,
       54.59815003, 54.59815003, 54.59815003, 54.59815003, 54.59